name: Python application

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    # Passos para build:
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install dependencies
        run: pip install -r requirements-dev.txt

      - name: Lint with flake8
        run: flake8 .

      - name: Test with pytest
        run: pytest cores_ft
